version: '3.6'

services:

  reverseproxy:
      image: 81318131/nginx-reverseproxy
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
       
        
  rembg:
    image: 81318131/rembg-server
    container_name: rembg
    command: rembg s
    volumes:
      - './u2net:/root/.u2net'
    ports:
      - "7000:7000"
    deploy:
      replicas: 4
   
  

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor:canary
    ports:
      - "8080:8080"
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices: 
      - "/dev/kmsg"


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
          - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090:9090'

    depends_on:
      - cadvisor

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.0
    container_name: prometheus-nginx-exporter
    command:
      - -nginx.scrape-uri=http://nginx/nginx_status
    expose: 
      - 9113
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
     - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost/grafana

      
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana
      
volumes:
  grafana-storage: {}

