scrape_configs:

  - job_name: 'docker'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.101.182:9323']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080'